#ifndef PRAT6_SHELL_H
#define PRAT6_SHELL_H

#include <vector>

// Shell sort original. Taken from https://en.wikipedia.org/wiki/Shellsort
std::vector<int> shell_sort_original(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Frank and Lazarus in 1960.
std::vector<int> shell_sort_frank_and_lazarus(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Hibbard in 1963.
std::vector<int> shell_sort_hibbard(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Papernov and Stasevich in 1965.
std::vector<int> shell_sort_papernov_stasevich(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Pratt in 1971.
std::vector<int> shell_sort_pratt(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Knuth in 1973.
std::vector<int> shell_sort_knuth(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Incerpi and Sedgewick in 1985.
std::vector<int> shell_sort_incerpi_sedgewick(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Sedgewick in 1982.
std::vector<int> shell_sort_sedgewick_1982(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Sedgewick in 1986.
std::vector<int> shell_sort_sedgewick_1986(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Gonnet and Baeza-Yates in 1991.
std::vector<int> shell_sort_gonnet_baeza_yates(std::vector<int> items);
// Shell sort with gaps generated by an algorithm invented by Tokuda in 1992.
std::vector<int> shell_sort_tokuda(std::vector<int> items);
// Shell sort with gaps found by Ciura in 2001
std::vector<int> shell_sort_ciura(std::vector<int> items);

#endif //PRAT6_SHELL_H
